name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ pkg-config libmariadb-dev libmariadb-dev-compat

      - name: Build
        run: |
          g++ main.cpp -o sistema_bancario $(pkg-config --cflags --libs mariadb)
